# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trpc.proto\x12\nrlmeta.rpc\"\x18\n\x05\x45rror\x12\x0f\n\x07message\x18\x01 \x01(\t\"<\n\nRpcRequest\x12\x10\n\x08\x66unction\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x01(\x0c\x12\x0e\n\x06kwargs\x18\x03 \x01(\x0c\"T\n\x0bRpcResponse\x12\x14\n\x0creturn_value\x18\x01 \x01(\x0c\x12%\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x11.rlmeta.rpc.ErrorH\x00\x88\x01\x01\x42\x08\n\x06_error2F\n\x03Rpc\x12?\n\nRemoteCall\x12\x16.rlmeta.rpc.RpcRequest\x1a\x17.rlmeta.rpc.RpcResponse\"\x00\x62\x06proto3')



_ERROR = DESCRIPTOR.message_types_by_name['Error']
_RPCREQUEST = DESCRIPTOR.message_types_by_name['RpcRequest']
_RPCRESPONSE = DESCRIPTOR.message_types_by_name['RpcResponse']
Error = _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), {
  'DESCRIPTOR' : _ERROR,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:rlmeta.rpc.Error)
  })
_sym_db.RegisterMessage(Error)

RpcRequest = _reflection.GeneratedProtocolMessageType('RpcRequest', (_message.Message,), {
  'DESCRIPTOR' : _RPCREQUEST,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:rlmeta.rpc.RpcRequest)
  })
_sym_db.RegisterMessage(RpcRequest)

RpcResponse = _reflection.GeneratedProtocolMessageType('RpcResponse', (_message.Message,), {
  'DESCRIPTOR' : _RPCRESPONSE,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:rlmeta.rpc.RpcResponse)
  })
_sym_db.RegisterMessage(RpcResponse)

_RPC = DESCRIPTOR.services_by_name['Rpc']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ERROR._serialized_start=25
  _ERROR._serialized_end=49
  _RPCREQUEST._serialized_start=51
  _RPCREQUEST._serialized_end=111
  _RPCRESPONSE._serialized_start=113
  _RPCRESPONSE._serialized_end=197
  _RPC._serialized_start=199
  _RPC._serialized_end=269
# @@protoc_insertion_point(module_scope)
