# Global configs
m_server_name: "m_server"
m_server_addr: "127.0.0.1:4411"

r_server_name: "r_server"
r_server_addr: "127.0.0.1:4412"

c_server_name: "c_server"
c_server_addr: "127.0.0.1:4413"

train_device: "cuda:0"
infer_device: "cuda:1"

env:
  game: "Pong"
  repeat_action_probability: 0.0  # v4
  max_num_frames_per_episode: 50000

seed: null
table_view: False

# Training configs.
num_training_rollouts: 32
num_training_workers: 16

replay_buffer_size: 262144
prefetch: 2

batch_size: 512

optimizer:
  name: "Adam"
  lr: 3e-4
  eps: 1e-8

learning_starts: 65536
model_push_period: 10

num_epochs: 1000
steps_per_epoch: 10000

# Evaluation configs
num_evaluation_episodes: 10

num_evaluation_rollouts: 4
num_evaluation_workers: 2

deterministic_evaluation: False
