m_server_name: "m_server"
m_server_addr: "127.0.0.1:4411"

r_server_name: "r_server"
r_server_addr: "127.0.0.1:4412"

c_server_name: "c_server"
c_server_addr: "127.0.0.1:4413"

train_device: "cuda:0"
infer_device: "cuda:1"

env:
  game: "Pong"
  repeat_action_probability: 0.0  # v4
  max_episode_steps: 10000

num_train_rollouts: 32
num_train_workers: 16

num_eval_rollouts: 4
num_eval_workers: 2

train_eps: 0.4
eval_eps: 0.01

replay_buffer_size: 1000000
priority_exponent: 0.6
prefetch: 2

importance_sampling_exponent: 0.4

max_abs_reward: 1
rescale_value: False
value_clipping_eps: 0.2

double_dqn: True
target_sync_period: 2500

batch_size: 512
n_step: 3
learning_starts: 65536
model_push_period: 10

optimizer:
  name: "Adam"
  args:
    lr: 1e-4

num_epochs: 1000
steps_per_epoch: 3000

num_eval_episodes: 10

seed: null

table_view: False
